/* 
Even Fibonacci numbers https://projecteuler.net/problem=2
Problem 2:
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million (4000000), find the sum of the even-valued terms.
*/

// JavaScript

var n = 3;
var i = 3;
var lista = [1, 2];
var soma = 2; // soma = 2 , porque o n começa em 3 e 2 é par

while (n < 4000000) {
    lista.push(n); 
    n = lista[i - 1] + lista[i - 2];
    i++;
    if (n % 2 === 0) {
        soma += n; // suma = suma + num3
    }
}

console.log(soma); // result: 4613732