/* 
Even Fibonacci numbers https://projecteuler.net/problem=2
Problem 2:
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million (4000000), find the sum of the even-valued terms.
*/

// JavaScript

let num1 = 1;
let num2 = 2;
let sum = 2; // soma = 2 , porque o n começa em 3 e 2 é par
let num3 = num1 + num2; 

while (num3 < 4000000) {
    num1 = num2;
    num2 = num3;
    num3 = num1 + num2;

    if (num3 % 2 == 0){
        sum += num3; // sum = sum + num3
    }
}

console.log(sum); // result: 4613732